name: itables-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - jupyter
  - jupyterlab
  - jupytext>=1.13.8
  - markdown-it-py>=2.0
  - nbconvert
  - ipykernel
  - pandas
  # Pytest
  - pytest
  - pytest-xdist
  - pytest-cov
  # Pre-commit & code quality
  - pre-commit
  - pylint
  - flake8
  - black
  - isort
  # Jupyter Lab extension
  - cookiecutter
  - nodejs
  - jupyter-packaging
  # Build
  - pip
  - setuptools
  - twine
  - build
  # Docs
  - ghp-import
  - pip:
    - world_bank_data
    - jupyter_book>=0.12  # jupyter-book-0.12.2-pyhd8ed1ab_0 requires jupytext >=1.11.2,<1.12
